import { db, functions } from '../firebase';
import { httpsCallable } from 'firebase/functions';
import {
  collection,
  addDoc,
  doc,
  setDoc,
  getDocs,
  query,
  where,
  orderBy,
  serverTimestamp,
  limit,
  onSnapshot,
  type Unsubscribe,
} from 'firebase/firestore';
import type { Visit, VisitData, Alert, GeoAnchor, DashboardMetrics, AgentLog } from '../types';
import { createLogger } from '../utils/logger';

const log = createLogger('DB');

// ---------------------------------------------------------------------------
// Writes
// ---------------------------------------------------------------------------

/** Saves a completed visit to Firestore. Alerts are created by the backend Verification Agent. */
export async function saveVisit(
  visitData: VisitData & { rawTranscription: string; geoAnchor: GeoAnchor | null; audioUrl?: string | null; locationName?: string; districtName?: string },
  userId: string
): Promise<string> {
  try {
    const visitsRef = collection(db, 'visits');
    const docRef = await addDoc(visitsRef, {
      ...visitData,
      workerId: userId,
      timestamp: serverTimestamp(),
    });
    log.info('Visit saved successfully', { visitId: docRef.id, household: visitData.householdName });
    return docRef.id;
  } catch (error) {
    log.error('Failed to save visit', error);
    throw error;
  }
}

/** Updates an existing visit in Firestore (e.g., marking as resolved). */
export async function updateVisit(
  visitId: string,
  data: Partial<Visit>
): Promise<void> {
  try {
    const visitRef = doc(db, 'visits', visitId);
    await setDoc(visitRef, data, { merge: true });
    log.info('Visit updated successfully', { visitId });
  } catch (error) {
    log.error('Failed to update visit', error);
    throw error;
  }
}


// ---------------------------------------------------------------------------
// Reads
// ---------------------------------------------------------------------------

/** Fetches recent visits for a specific field worker (one-time read). */
export async function getRecentVisits(userId: string): Promise<Visit[]> {
  try {
    const visitsRef = collection(db, 'visits');
    const q = query(visitsRef, where('workerId', '==', userId), orderBy('timestamp', 'desc'));
    const snapshot = await getDocs(q);
    return snapshot.docs.map((doc) => ({ id: doc.id, ...doc.data() }) as Visit);
  } catch (error) {
    log.error('Failed to fetch recent visits', error);
    throw error;
  }
}

// ---------------------------------------------------------------------------
// Real-Time Listeners
// ---------------------------------------------------------------------------

/** Subscribes to the latest 50 visits across all workers. */
export function onVisitsSnapshot(callback: (visits: Visit[]) => void): Unsubscribe {
  const visitsRef = collection(db, 'visits');
  const q = query(visitsRef, orderBy('timestamp', 'desc'), limit(500));
  return onSnapshot(
    q,
    (snapshot) => {
      const visits = snapshot.docs.map((doc) => ({ id: doc.id, ...doc.data() }) as Visit);
      callback(visits);
    },
    (error) => {
      log.error('Real-time visits listener error', error);
      callback([]);
    }
  );
}

/** Listen to real-time updates for all Agent Orchestration Logs */
export function onAgentLogsSnapshot(callback: (logs: AgentLog[]) => void): Unsubscribe {
  const logsRef = collection(db, 'agent_logs');
  const q = query(logsRef, orderBy('timestamp', 'desc'), limit(50));
  
  return onSnapshot(q, (snapshot) => {
    const logs = snapshot.docs.map(doc => ({ id: doc.id, ...doc.data() }) as AgentLog);
    callback(logs);
  });
}

/** Listen to real-time updates for District AI Analytics generated by Analytics Agent */
export function onAnalyticsSnapshot(location: string, callback: (data: any) => void): Unsubscribe {
  const analyticsRef = doc(db, 'analytics', location);
  
  return onSnapshot(analyticsRef, (snapshot) => {
    if (snapshot.exists()) {
      callback(snapshot.data());
    } else {
      callback(null);
    }
  });
}

/** Subscribes to visits flagged by the Verification Agent. */
export function onFlaggedVisitsSnapshot(callback: (visits: Visit[]) => void): Unsubscribe {
  const visitsRef = collection(db, 'visits');
  const q = query(
    visitsRef,
    where('anomaliesFound', '==', true),
    orderBy('timestamp', 'desc'),
    limit(20)
  );
  return onSnapshot(
    q,
    (snapshot) => {
      const visits = snapshot.docs.map((doc) => ({ id: doc.id, ...doc.data() }) as Visit);
      callback(visits);
    },
    (error) => {
      log.error('Real-time flagged visits listener error', error);
      callback([]);
    }
  );
}

/** Subscribes to supervisor alerts (created by backend Verification Agent). */
export function onAlertsSnapshot(callback: (alerts: Alert[]) => void): Unsubscribe {
  const alertsRef = collection(db, 'alerts');
  const q = query(alertsRef, orderBy('timestamp', 'desc'), limit(10));
  return onSnapshot(
    q,
    (snapshot) => {
      const alerts = snapshot.docs.map((doc) => ({ id: doc.id, ...doc.data() }) as Alert);
      callback(alerts);
    },
    (error) => {
      log.error('Real-time alerts listener error', error);
      callback([]);
    }
  );
}

// ---------------------------------------------------------------------------
// One-Time Reads
// ---------------------------------------------------------------------------

/** Fetches the latest 10 supervisor alerts (one-time read). */
export async function getSupervisorAlerts(): Promise<Alert[]> {
  try {
    const alertsRef = collection(db, 'alerts');
    const q = query(alertsRef, orderBy('timestamp', 'desc'), limit(10));
    const snapshot = await getDocs(q);
    return snapshot.docs.map((doc) => ({ id: doc.id, ...doc.data() }) as Alert);
  } catch (error) {
    log.error('Failed to fetch supervisor alerts', error);
    return [];
  }
}

/** Fetches all flagged visits (one-time read). */
export async function getFlaggedVisits(): Promise<Visit[]> {
  try {
    const visitsRef = collection(db, 'visits');
    const q = query(
      visitsRef,
      where('anomaliesFound', '==', true),
      orderBy('timestamp', 'desc'),
      limit(20)
    );
    const snapshot = await getDocs(q);
    return snapshot.docs.map((doc) => ({ id: doc.id, ...doc.data() }) as Visit);
  } catch (error) {
    log.error('Failed to fetch flagged visits', error);
    return [];
  }
}

/** Fetches all visits (one-time read). */
export async function getAllVisits(): Promise<Visit[]> {
  try {
    const visitsRef = collection(db, 'visits');
    const q = query(visitsRef, orderBy('timestamp', 'desc'), limit(50));
    const snapshot = await getDocs(q);
    return snapshot.docs.map((doc) => ({ id: doc.id, ...doc.data() }) as Visit);
  } catch (error) {
    log.error('Failed to fetch all visits', error);
    return [];
  }
}

// ---------------------------------------------------------------------------
// BigQuery Analytics (via Cloud Function)
// ---------------------------------------------------------------------------

/** Calls the getDHOMetrics Cloud Function to fetch aggregated analytics. */
export async function fetchDHOAnalytics(): Promise<DashboardMetrics> {
  try {
    const getDHOMetrics = httpsCallable<void, DashboardMetrics>(functions, 'getDHOMetrics');
    const result = await getDHOMetrics();
    log.info('DHO analytics fetched from BigQuery');
    return result.data;
  } catch (error) {
    log.error('BigQuery analytics unavailable', error);
    throw error;
  }
}

// ---------------------------------------------------------------------------
// FCM Token Management
// ---------------------------------------------------------------------------

export async function saveFCMToken(userId: string, token: string): Promise<void> {
  try {
    const workerRef = doc(db, 'workers', userId);
    await setDoc(workerRef, { fcmToken: token, updatedAt: serverTimestamp() }, { merge: true });
    log.info('FCM Token saved for worker', { userId });
  } catch (error) {
    log.error('Failed to save FCM token', error);
  }
}

// ---------------------------------------------------------------------------
// Cloud Storage (Audio Logs)
// ---------------------------------------------------------------------------

export async function uploadAudioLog(audioBlob: Blob, userId: string): Promise<string> {
  try {
    log.info('Converting audio to Base64 for Firestore storage', { userId, size: audioBlob.size });
    
    // Enterprise Offline-First Solution: Store as Base64 Data URL directly in Firestore
    // This bypasses Firebase Storage completely, eliminating CORS issues and ensuring 
    // the audio is fully available offline via Firestore's persistent cache.
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.readAsDataURL(audioBlob);
      reader.onloadend = () => {
        if (typeof reader.result === 'string') {
          log.info('Audio converted to Data URL successfully');
          resolve(reader.result);
        } else {
          reject(new Error('Failed to convert audio to base64 string'));
        }
      };
      reader.onerror = reject;
    });
  } catch (error) {
    log.error('Failed to process audio log', error);
    throw error;
  }
}
